apiVersion: apps/v1
kind: Deployment
metadata:
  name: book_web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book_web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: book_web
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: book_web
          image:  {{ACR_LOGINSERVER}}/book_web:v{{BUILD_NUMBER}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: book_web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: book_web